---
apiVersion: v1
kind: Namespace
metadata:
  name: web

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      name: webapp
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp-container
          image: 76896/afriprudentialtest:latest
          imagePullPolicy: Always
          args:
          - /bin/sh
          - -c
          - touch /tmp/healthz; sleep 3600         
          ports:
          - containerPort: 8080
          livenessProbe:              
          httpGet:
            path: /tmp/healthz
            port: 8081
            targetPort: 8080
          failureThreshold: 3
          initiatlDelaySeconds: 20
          periodSeconds: 15         
          readinessProbe:
          tcpSocket:
            port: 80
            targetPort: 8080
          initialDelaySeconds: 45 

---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: webapp
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    name: http
    nodePort: 30080
  selector:
    matchLabels: webapp
    app: webapp
